name: Test workflow

on:
  pull_request:
    branches: main

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "hello world!"

  check-commit-author:
    needs: echo-hello-world
    runs-on: ubuntu-latest

    # This is how you set up output mapping
    outputs:
      commit-author: ${{ steps.check.outputs.author }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get previous commit author

        # The 'id' field is needed to map the outputs properly
        # The 'id' is how you identify which step the output is coming from
        id: check

        # The key 'author' needs to match the output name mentioned
        # in the outputs map earlier (steps.check.outputs."author")
        run: echo "author=$(git show -s | grep Author)" >> $GITHUB_OUTPUT

      - name: Print previous commit author
        run: echo "Previous ${{ steps.check.outputs.author }}"

      - name: Get workflow actor username
        run: echo "${{ github.actor }}"

  increment-counter:
    needs: check-commit-author
    runs-on: ubuntu-latest

    # Run this job based on what's in the commit-author output variable
    if: ${{ ! contains(needs.check-commit-author.outputs.commit-author, 'github-actions[bot]') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

          # You have to specify your Personal Access Token (PAT) here!
          # AUTO_INC is the name of my PAT, accessed via 'secrets' global variable
          token: ${{ secrets.NO_PERMS }}

      - name: Increment counter
        run: |
          echo $(cat counter)
          echo $(($(cat counter) + 1)) > counter
          echo $(cat counter)

      - name: Create Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@user.noreply.github.com'
          git commit -a -m "Incremented counter [github-actions[bot]]"
          git push

  finish-workflow:
    needs: increment-counter
    runs-on: ubuntu-latest
    steps:
      - name: print goodbye world
        run: echo "goodbye world"
