name: Test workflow

on:
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "hello world!"

  check-commit-author:
    needs: [echo-hello-world]
    runs-on: ubuntu-latest
    outputs:
      author: ${{ steps.check.outputs.author }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get previous commit author
        id: check
        run: echo author=$(git show -s | grep AUTHOR) >> $GITHUB_OUTPUT

  increment-counter:
    needs: [check-commit-author]
    runs-on: ubuntu-latest
    if: ${{ ! contains(needs.check-commit-author.outputs.author, 'github-actions[bot]') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.AUTO_INC }}

      - name: Analylze current directory
        run: |
          echo $(pwd)
          echo $(ls)
          echo "the goat ${{ needs.check-commit-author.outputs.author }}"

      - name: Print counter
        run: echo $(cat counter)

      - name: Increment counter
        run: echo $(($(cat counter) + 1)) > counter

      - name: Print updated counter
        run: echo $(cat counter)

      - name: Create Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@user.noreply.github.com'
          git commit -a -m "Incremented counter [github-actions[bot]]"
          # git push

  finish-workflow:
    needs: [increment-counter]
    runs-on: ubuntu-latest
    steps:
      - name: print goodbye world
        run: echo goodbye world
