name: Test workflow

on:
  pull_request:
    branches: main

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "hello world!"

  increment-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Print counter
        run: echo $(cat counter)

      - name: Increment and push counter
        run: |
          $($(cat counter) + 1) > counter
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@user.noreply.github.com'
          git commit -a -m "Incremented counter"
          git push

  finish-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: print goodbye world
        run: echo goodbye world
